package io.github.shootgame.network

import java.nio.ByteBuffer
import java.nio.ByteOrder

/**
 * Wire codec shared with the Rust server (see docs/wire-protocol.md).
 *
 * Framing:
 *   TCP:  [ len:u32 LE ][ type:u8 ][ protobuf body ]
 *   UDP:                [ type:u8 ][ protobuf body ]
 *
 * Protobuf types are generated by the protobuf Gradle plugin from
 * shootgame.proto into package `io.github.shootgame.proto`.
 */
object Wire {
    /** Wire type tags — must match the Rust server. */
    const val TYPE_LOGIN: Byte = 1
    const val TYPE_LOGIN_RESPONSE: Byte = 2
    const val TYPE_PLAYER_STATE: Byte = 3
    const val TYPE_PLAYER_SHOOT: Byte = 4
    const val TYPE_PLAYER_HIT: Byte = 5
    const val TYPE_PLAYER_CONNECTED: Byte = 6
    const val TYPE_PLAYER_DISCONNECTED: Byte = 7
    const val TYPE_REGISTER: Byte = 8

    /** Build a TCP frame: [len][type][body]. */
    fun tcpFrame(type: Byte, body: com.google.protobuf.MessageLite): ByteArray {
        val payload = body.toByteArray()
        val out = ByteBuffer.allocate(4 + 1 + payload.size).order(ByteOrder.LITTLE_ENDIAN)
        out.putInt(1 + payload.size) // len = type + body
        out.put(type)
        out.put(payload)
        return out.array()
    }

    /** Build a UDP datagram: [type][body]. */
    fun udpDatagram(type: Byte, body: com.google.protobuf.MessageLite): ByteArray {
        val payload = body.toByteArray()
        val out = ByteBuffer.allocate(1 + payload.size)
        out.put(type)
        out.put(payload)
        return out.array()
    }

    /** UDP registration datagram: [0x08][ id:u32 LE ]. */
    fun registerDatagram(id: Int): ByteArray {
        val out = ByteBuffer.allocate(5).order(ByteOrder.LITTLE_ENDIAN)
        out.put(TYPE_REGISTER)
        out.putInt(id)
        return out.array()
    }

    /** Read exactly n bytes into a buffer, or null on EOF. */
    private fun readFully(input: java.io.InputStream, n: Int): ByteArray? {
        val buf = ByteArray(n)
        var read = 0
        while (read < n) {
            val r = input.read(buf, read, n - read)
            if (r < 0) return null
            read += r
        }
        return buf
    }

    /**
     * Read one TCP frame and return its (type, body) pair, or null on EOF.
     */
    fun readFrame(input: java.io.InputStream): Pair<Byte, ByteArray>? {
        val lenBytes = readFully(input, 4) ?: return null
        val len = ByteBuffer.wrap(lenBytes).order(ByteOrder.LITTLE_ENDIAN).int
        val frame = readFully(input, len) ?: return null
        val type = frame[0]
        val body = frame.copyOfRange(1, frame.size)
        return type to body
    }

    /** Read one UDP datagram and return its (type, body) pair. */
    fun readDatagram(packet: java.net.DatagramPacket): Pair<Byte, ByteArray> {
        val data = packet.data
        val len = packet.length
        val type = data[0]
        val body = data.copyOfRange(1, len)
        return type to body
    }
}
